// Generated by `Make.save()`. Do not edit.

import { z } from 'zod'
import type {
  GetAverage,
  GetAverageTake,
  GetCount,
  GetCountTake,
  GetFirst,
  GetFirstTake,
  GetLargest,
  GetLargestTake,
  GetLast,
  GetLastTake,
  GetLength,
  GetLengthTake,
  GetSmallest,
  GetSmallestTake,
  GetSum,
  GetSumTake,
} from '.'

export const GetAverageTakeForm = z.object({
  numbers: z.array(z.number()),
}) satisfies z.ZodType<GetAverageTake>
export const GetAverageForm = z.number() satisfies z.ZodType<GetAverage>

export const GetCountTakeForm = z.object({
  items: z.array(z.unknown()),
}) satisfies z.ZodType<GetCountTake>
export const GetCountForm = z.number() satisfies z.ZodType<GetCount>

export const GetFirstTakeForm = z.object({
  items: z.array(z.unknown()),
}) satisfies z.ZodType<GetFirstTake>
export const GetFirstForm = z.unknown() satisfies z.ZodType<GetFirst>

export const GetLargestTakeForm = z.object({
  numbers: z.array(z.number()),
}) satisfies z.ZodType<GetLargestTake>
export const GetLargestForm = z.number() satisfies z.ZodType<GetLargest>

export const GetLastTakeForm = z.object({
  items: z.array(z.unknown()),
}) satisfies z.ZodType<GetLastTake>
export const GetLastForm = z.unknown() satisfies z.ZodType<GetLast>

export const GetLengthTakeForm = z.object({
  text: z.string(),
}) satisfies z.ZodType<GetLengthTake>
export const GetLengthForm = z.number() satisfies z.ZodType<GetLength>

export const GetSmallestTakeForm = z.object({
  numbers: z.array(z.number()),
}) satisfies z.ZodType<GetSmallestTake>
export const GetSmallestForm = z.number() satisfies z.ZodType<GetSmallest>

export const GetSumTakeForm = z.object({
  numbers: z.array(z.number()),
}) satisfies z.ZodType<GetSumTake>
export const GetSumForm = z.number() satisfies z.ZodType<GetSum>
