// Generated by `Make.save()`. Do not edit.

export type GetAverageTake = { numbers: number[] }
export type GetAverage = number

export type GetCountTake = { items: unknown[] }
export type GetCount = number

export type GetFirstTake = { items: unknown[] }
export type GetFirst = unknown

export type GetLargestTake = { numbers: number[] }
export type GetLargest = number

export type GetLastTake = { items: unknown[] }
export type GetLast = unknown

export type GetLengthTake = { text: string }
export type GetLength = number

export type GetSmallestTake = { numbers: number[] }
export type GetSmallest = number

export type GetSumTake = { numbers: number[] }
export type GetSum = number
