// Generated by `Make.save()`. Do not edit.

export type Code = {
  'flow:is:always_false': { take: unknown; make: boolean }
  'flow:is:always_true': { take: unknown; make: boolean }
  'flow:is:above': { take: { this: unknown; that: unknown }; make: boolean }
  'flow:is:all': { take: { things: boolean[] }; make: boolean }
  'flow:is:among': { take: { thing: unknown; choices: unknown[] }; make: boolean }
  'flow:is:any': { take: { things: boolean[] }; make: boolean }
  'flow:is:below': { take: { this: unknown; that: unknown }; make: boolean }
  'flow:is:between': { take: { thing: unknown; min: unknown; max: unknown }; make: boolean }
  'flow:is:blank': { take: { thing: unknown }; make: boolean }
  'flow:is:boolean': { take: { thing: unknown }; make: boolean }
  'flow:is:decimal': { take: { thing: unknown }; make: boolean }
  'flow:is:email': { take: { text: string }; make: boolean }
  'flow:is:equal': { take: { this: unknown; that: unknown }; make: boolean }
  'flow:is:finite': { take: { number: number }; make: boolean }
  'flow:is:integer': { take: { thing: unknown }; make: boolean }
  'flow:is:ipa': { take: { text: string }; make: boolean }
  'flow:is:ipa:broad': { take: { text: string }; make: boolean }
  'flow:is:ipa:narrow': { take: { text: string }; make: boolean }
  'flow:is:list': { take: { thing: unknown }; make: boolean }
  'flow:is:lowercase': { take: { text: string }; make: boolean }
  'flow:is:map': { take: { thing: unknown }; make: boolean }
  'flow:is:max': { take: { this: unknown; that: unknown }; make: boolean }
  'flow:is:min': { take: { this: unknown; that: unknown }; make: boolean }
  'flow:is:negative': { take: { number: number }; make: boolean }
  'flow:is:not': { take: { thing: boolean }; make: boolean }
  'flow:is:null': { take: { thing: unknown }; make: boolean }
  'flow:is:one': { take: { things: boolean[] }; make: boolean }
  'flow:is:positive': { take: { number: number }; make: boolean }
  'flow:is:slug': { take: { text: string }; make: boolean }
  'flow:is:string': { take: { thing: unknown }; make: boolean }
  'flow:is:uppercase': { take: { text: string }; make: boolean }
  'flow:is:url': { take: { text: string }; make: boolean }
  'flow:is:uuid': { take: { text: string }; make: boolean }
  'flow:is:whole': { take: { number: number }; make: boolean }
  'flow:is:zero': { take: { number: number }; make: boolean }
  'flow:make:difference': { take: { a: number; b: number }; make: number }
  'flow:make:lowercase': { take: { text: string }; make: string }
  'flow:make:product': { take: { a: number; b: number }; make: number }
  'flow:make:quotient': { take: { a: number; b: number }; make: number }
  'flow:make:sum': { take: { a: number; b: number }; make: number }
  'flow:make:trimmed': { take: { text: string }; make: string }
  'flow:make:uppercase': { take: { text: string }; make: string }
  'flow:get:average': { take: { numbers: number[] }; make: number }
  'flow:get:count': { take: { items: unknown[] }; make: number }
  'flow:get:first': { take: { items: unknown[] }; make: unknown }
  'flow:get:largest': { take: { numbers: number[] }; make: number }
  'flow:get:last': { take: { items: unknown[] }; make: unknown }
  'flow:get:length': { take: { text: string }; make: number }
  'flow:get:smallest': { take: { numbers: number[] }; make: number }
  'flow:get:sum': { take: { numbers: number[] }; make: number }
  'flow:has:item': { take: { items: unknown[]; item: unknown }; make: boolean }
  'flow:has:key': { take: { thing: unknown; key: string }; make: boolean }
  'flow:has:keys': { take: { thing: unknown; keys: string[] }; make: boolean }
  'flow:has:pattern': { take: { text: string; pattern: string }; make: boolean }
  'flow:has:prefix': { take: { text: string; prefix: string }; make: boolean }
  'flow:has:substring': { take: { text: string; substring: string }; make: boolean }
  'flow:has:suffix': { take: { text: string; suffix: string }; make: boolean }
  'flow:has:value': { take: { thing: unknown; value: unknown }; make: boolean }
}

export default Code
