// Generated by `Make.save()`. Do not edit.

import type { GetAverage, GetAverageTake, GetCount, GetCountTake, GetFirst, GetFirstTake, GetLargest, GetLargestTake, GetLast, GetLastTake, GetLength, GetLengthTake, GetSmallest, GetSmallestTake, GetSum, GetSumTake } from './get'
import type { HasItem, HasItemTake, HasKey, HasKeyTake, HasKeys, HasKeysTake, HasPattern, HasPatternTake, HasPrefix, HasPrefixTake, HasSubstring, HasSubstringTake, HasSuffix, HasSuffixTake, HasValue, HasValueTake } from './has'
import type { IsAbove, IsAboveTake, IsAll, IsAllTake, IsAlwaysFalse, IsAlwaysFalseTake, IsAlwaysTrue, IsAlwaysTrueTake, IsAmong, IsAmongTake, IsAny, IsAnyTake, IsBelow, IsBelowTake, IsBetween, IsBetweenTake, IsBlank, IsBlankTake, IsBoolean, IsBooleanTake, IsDecimal, IsDecimalTake, IsEmail, IsEmailTake, IsEqual, IsEqualTake, IsFinite, IsFiniteTake, IsInteger, IsIntegerTake, IsIpa, IsIpaBroad, IsIpaBroadTake, IsIpaNarrow, IsIpaNarrowTake, IsIpaTake, IsList, IsListTake, IsLowercase, IsLowercaseTake, IsMap, IsMapTake, IsMax, IsMaxTake, IsMin, IsMinTake, IsNegative, IsNegativeTake, IsNot, IsNotTake, IsNull, IsNullTake, IsOne, IsOneTake, IsPositive, IsPositiveTake, IsSlug, IsSlugTake, IsString, IsStringTake, IsUppercase, IsUppercaseTake, IsUrl, IsUrlTake, IsUuid, IsUuidTake, IsWhole, IsWholeTake, IsZero, IsZeroTake } from './is'
import type { MakeDifference, MakeDifferenceTake, MakeLowercase, MakeLowercaseTake, MakeProduct, MakeProductTake, MakeQuotient, MakeQuotientTake, MakeSum, MakeSumTake, MakeTrimmed, MakeTrimmedTake, MakeUppercase, MakeUppercaseTake } from './make'

export type Code = {
  'flow:is:always_false': { take: IsAlwaysFalseTake; make: IsAlwaysFalse }
  'flow:is:always_true': { take: IsAlwaysTrueTake; make: IsAlwaysTrue }
  'flow:is:above': { take: IsAboveTake; make: IsAbove }
  'flow:is:all': { take: IsAllTake; make: IsAll }
  'flow:is:among': { take: IsAmongTake; make: IsAmong }
  'flow:is:any': { take: IsAnyTake; make: IsAny }
  'flow:is:below': { take: IsBelowTake; make: IsBelow }
  'flow:is:between': { take: IsBetweenTake; make: IsBetween }
  'flow:is:blank': { take: IsBlankTake; make: IsBlank }
  'flow:is:boolean': { take: IsBooleanTake; make: IsBoolean }
  'flow:is:decimal': { take: IsDecimalTake; make: IsDecimal }
  'flow:is:email': { take: IsEmailTake; make: IsEmail }
  'flow:is:equal': { take: IsEqualTake; make: IsEqual }
  'flow:is:finite': { take: IsFiniteTake; make: IsFinite }
  'flow:is:integer': { take: IsIntegerTake; make: IsInteger }
  'flow:is:ipa': { take: IsIpaTake; make: IsIpa }
  'flow:is:ipa:broad': { take: IsIpaBroadTake; make: IsIpaBroad }
  'flow:is:ipa:narrow': { take: IsIpaNarrowTake; make: IsIpaNarrow }
  'flow:is:list': { take: IsListTake; make: IsList }
  'flow:is:lowercase': { take: IsLowercaseTake; make: IsLowercase }
  'flow:is:map': { take: IsMapTake; make: IsMap }
  'flow:is:max': { take: IsMaxTake; make: IsMax }
  'flow:is:min': { take: IsMinTake; make: IsMin }
  'flow:is:negative': { take: IsNegativeTake; make: IsNegative }
  'flow:is:not': { take: IsNotTake; make: IsNot }
  'flow:is:null': { take: IsNullTake; make: IsNull }
  'flow:is:one': { take: IsOneTake; make: IsOne }
  'flow:is:positive': { take: IsPositiveTake; make: IsPositive }
  'flow:is:slug': { take: IsSlugTake; make: IsSlug }
  'flow:is:string': { take: IsStringTake; make: IsString }
  'flow:is:uppercase': { take: IsUppercaseTake; make: IsUppercase }
  'flow:is:url': { take: IsUrlTake; make: IsUrl }
  'flow:is:uuid': { take: IsUuidTake; make: IsUuid }
  'flow:is:whole': { take: IsWholeTake; make: IsWhole }
  'flow:is:zero': { take: IsZeroTake; make: IsZero }
  'flow:make:difference': { take: MakeDifferenceTake; make: MakeDifference }
  'flow:make:lowercase': { take: MakeLowercaseTake; make: MakeLowercase }
  'flow:make:product': { take: MakeProductTake; make: MakeProduct }
  'flow:make:quotient': { take: MakeQuotientTake; make: MakeQuotient }
  'flow:make:sum': { take: MakeSumTake; make: MakeSum }
  'flow:make:trimmed': { take: MakeTrimmedTake; make: MakeTrimmed }
  'flow:make:uppercase': { take: MakeUppercaseTake; make: MakeUppercase }
  'flow:get:average': { take: GetAverageTake; make: GetAverage }
  'flow:get:count': { take: GetCountTake; make: GetCount }
  'flow:get:first': { take: GetFirstTake; make: GetFirst }
  'flow:get:largest': { take: GetLargestTake; make: GetLargest }
  'flow:get:last': { take: GetLastTake; make: GetLast }
  'flow:get:length': { take: GetLengthTake; make: GetLength }
  'flow:get:smallest': { take: GetSmallestTake; make: GetSmallest }
  'flow:get:sum': { take: GetSumTake; make: GetSum }
  'flow:has:item': { take: HasItemTake; make: HasItem }
  'flow:has:key': { take: HasKeyTake; make: HasKey }
  'flow:has:keys': { take: HasKeysTake; make: HasKeys }
  'flow:has:pattern': { take: HasPatternTake; make: HasPattern }
  'flow:has:prefix': { take: HasPrefixTake; make: HasPrefix }
  'flow:has:substring': { take: HasSubstringTake; make: HasSubstring }
  'flow:has:suffix': { take: HasSuffixTake; make: HasSuffix }
  'flow:has:value': { take: HasValueTake; make: HasValue }
}

export const CodeLink = {
  'flow:get:average': 1,
  'flow:get:count': 2,
  'flow:get:first': 3,
  'flow:get:largest': 4,
  'flow:get:last': 5,
  'flow:get:length': 6,
  'flow:get:smallest': 7,
  'flow:get:sum': 8,
  'flow:has:item': 9,
  'flow:has:key': 10,
  'flow:has:keys': 11,
  'flow:has:pattern': 12,
  'flow:has:prefix': 13,
  'flow:has:substring': 14,
  'flow:has:suffix': 15,
  'flow:has:value': 16,
  'flow:is:above': 17,
  'flow:is:all': 18,
  'flow:is:always_false': 19,
  'flow:is:always_true': 20,
  'flow:is:among': 21,
  'flow:is:any': 22,
  'flow:is:below': 23,
  'flow:is:between': 24,
  'flow:is:blank': 25,
  'flow:is:boolean': 26,
  'flow:is:decimal': 27,
  'flow:is:email': 28,
  'flow:is:equal': 29,
  'flow:is:finite': 30,
  'flow:is:integer': 31,
  'flow:is:ipa': 32,
  'flow:is:ipa:broad': 33,
  'flow:is:ipa:narrow': 34,
  'flow:is:list': 35,
  'flow:is:lowercase': 36,
  'flow:is:map': 37,
  'flow:is:max': 38,
  'flow:is:min': 39,
  'flow:is:negative': 40,
  'flow:is:not': 41,
  'flow:is:null': 42,
  'flow:is:one': 43,
  'flow:is:positive': 44,
  'flow:is:slug': 45,
  'flow:is:string': 46,
  'flow:is:uppercase': 47,
  'flow:is:url': 48,
  'flow:is:uuid': 49,
  'flow:is:whole': 50,
  'flow:is:zero': 51,
  'flow:make:difference': 52,
  'flow:make:lowercase': 53,
  'flow:make:product': 54,
  'flow:make:quotient': 55,
  'flow:make:sum': 56,
  'flow:make:trimmed': 57,
  'flow:make:uppercase': 58,
} as const

export type CodeLink = (typeof CodeLink)[keyof typeof CodeLink]

export default Code
