// Generated by `Make.save()`. Do not edit.

export type Code = {
  'flow:is:always_false': { take: unknown; make: boolean }
  'flow:is:always_true': { take: unknown; make: boolean }
  'flow:is:above': { take: { this: unknown; that: unknown }; make: boolean }
  'flow:is:all': { take: { things: boolean[] }; make: boolean }
  'flow:is:among': { take: { thing: unknown; choices: unknown[] }; make: boolean }
  'flow:is:any': { take: { things: boolean[] }; make: boolean }
  'flow:is:below': { take: { this: unknown; that: unknown }; make: boolean }
  'flow:is:between': { take: { thing: unknown; min: unknown; max: unknown }; make: boolean }
  'flow:is:blank': { take: { thing: unknown }; make: boolean }
  'flow:is:boolean': { take: { thing: unknown }; make: boolean }
  'flow:is:decimal': { take: { thing: unknown }; make: boolean }
  'flow:is:email': { take: { text: string }; make: boolean }
  'flow:is:equal': { take: { this: unknown; that: unknown }; make: boolean }
  'flow:is:finite': { take: { number: number }; make: boolean }
  'flow:is:integer': { take: { thing: unknown }; make: boolean }
  'flow:is:ipa': { take: { text: string }; make: boolean }
  'flow:is:ipa:broad': { take: { text: string }; make: boolean }
  'flow:is:ipa:narrow': { take: { text: string }; make: boolean }
  'flow:is:list': { take: { thing: unknown }; make: boolean }
  'flow:is:lowercase': { take: { text: string }; make: boolean }
  'flow:is:map': { take: { thing: unknown }; make: boolean }
  'flow:is:max': { take: { this: unknown; that: unknown }; make: boolean }
  'flow:is:min': { take: { this: unknown; that: unknown }; make: boolean }
  'flow:is:negative': { take: { number: number }; make: boolean }
  'flow:is:not': { take: { thing: boolean }; make: boolean }
  'flow:is:null': { take: { thing: unknown }; make: boolean }
  'flow:is:one': { take: { things: boolean[] }; make: boolean }
  'flow:is:positive': { take: { number: number }; make: boolean }
  'flow:is:slug': { take: { text: string }; make: boolean }
  'flow:is:string': { take: { thing: unknown }; make: boolean }
  'flow:is:uppercase': { take: { text: string }; make: boolean }
  'flow:is:url': { take: { text: string }; make: boolean }
  'flow:is:uuid': { take: { text: string }; make: boolean }
  'flow:is:whole': { take: { number: number }; make: boolean }
  'flow:is:zero': { take: { number: number }; make: boolean }
  'flow:make:difference': { take: { a: number; b: number }; make: number }
  'flow:make:lowercase': { take: { text: string }; make: string }
  'flow:make:product': { take: { a: number; b: number }; make: number }
  'flow:make:quotient': { take: { a: number; b: number }; make: number }
  'flow:make:sum': { take: { a: number; b: number }; make: number }
  'flow:make:trimmed': { take: { text: string }; make: string }
  'flow:make:uppercase': { take: { text: string }; make: string }
  'flow:get:average': { take: { numbers: number[] }; make: number }
  'flow:get:count': { take: { items: unknown[] }; make: number }
  'flow:get:first': { take: { items: unknown[] }; make: unknown }
  'flow:get:largest': { take: { numbers: number[] }; make: number }
  'flow:get:last': { take: { items: unknown[] }; make: unknown }
  'flow:get:length': { take: { text: string }; make: number }
  'flow:get:smallest': { take: { numbers: number[] }; make: number }
  'flow:get:sum': { take: { numbers: number[] }; make: number }
  'flow:has:item': { take: { items: unknown[]; item: unknown }; make: boolean }
  'flow:has:key': { take: { thing: unknown; key: string }; make: boolean }
  'flow:has:keys': { take: { thing: unknown; keys: string[] }; make: boolean }
  'flow:has:pattern': { take: { text: string; pattern: string }; make: boolean }
  'flow:has:prefix': { take: { text: string; prefix: string }; make: boolean }
  'flow:has:substring': { take: { text: string; substring: string }; make: boolean }
  'flow:has:suffix': { take: { text: string; suffix: string }; make: boolean }
  'flow:has:value': { take: { thing: unknown; value: unknown }; make: boolean }
}

export const CodeLink = {
  'flow:get:average': 1,
  'flow:get:count': 2,
  'flow:get:first': 3,
  'flow:get:largest': 4,
  'flow:get:last': 5,
  'flow:get:length': 6,
  'flow:get:smallest': 7,
  'flow:get:sum': 8,
  'flow:has:item': 9,
  'flow:has:key': 10,
  'flow:has:keys': 11,
  'flow:has:pattern': 12,
  'flow:has:prefix': 13,
  'flow:has:substring': 14,
  'flow:has:suffix': 15,
  'flow:has:value': 16,
  'flow:is:above': 17,
  'flow:is:all': 18,
  'flow:is:always_false': 19,
  'flow:is:always_true': 20,
  'flow:is:among': 21,
  'flow:is:any': 22,
  'flow:is:below': 23,
  'flow:is:between': 24,
  'flow:is:blank': 25,
  'flow:is:boolean': 26,
  'flow:is:decimal': 27,
  'flow:is:email': 28,
  'flow:is:equal': 29,
  'flow:is:finite': 30,
  'flow:is:integer': 31,
  'flow:is:ipa': 32,
  'flow:is:ipa:broad': 33,
  'flow:is:ipa:narrow': 34,
  'flow:is:list': 35,
  'flow:is:lowercase': 36,
  'flow:is:map': 37,
  'flow:is:max': 38,
  'flow:is:min': 39,
  'flow:is:negative': 40,
  'flow:is:not': 41,
  'flow:is:null': 42,
  'flow:is:one': 43,
  'flow:is:positive': 44,
  'flow:is:slug': 45,
  'flow:is:string': 46,
  'flow:is:uppercase': 47,
  'flow:is:url': 48,
  'flow:is:uuid': 49,
  'flow:is:whole': 50,
  'flow:is:zero': 51,
  'flow:make:difference': 52,
  'flow:make:lowercase': 53,
  'flow:make:product': 54,
  'flow:make:quotient': 55,
  'flow:make:sum': 56,
  'flow:make:trimmed': 57,
  'flow:make:uppercase': 58,
} as const

export type CodeLink = (typeof CodeLink)[keyof typeof CodeLink]

export default Code
