// Generated by `Make.save()`. Do not edit.

import type { Bind, BindTake } from './bind'
import type { Branch, BranchTake } from './branch'
import type {
  FormatCapitalized,
  FormatCapitalizedTake,
  FormatCurrency,
  FormatCurrencyTake,
  FormatDate,
  FormatDateTake,
  FormatJoined,
  FormatJoinedTake,
  FormatLowercase,
  FormatLowercaseTake,
  FormatNumber,
  FormatNumberTake,
  FormatPercent,
  FormatPercentTake,
  FormatPlural,
  FormatPluralTake,
  FormatRelative,
  FormatRelativeTake,
  FormatReplaced,
  FormatReplacedTake,
  FormatReversed,
  FormatReversedTake,
  FormatSplit,
  FormatSplitTake,
  FormatTime,
  FormatTimeTake,
  FormatTruncated,
  FormatTruncatedTake,
  FormatUppercase,
  FormatUppercaseTake,
} from './format'
import type {
  GetAverage,
  GetAverageTake,
  GetCount,
  GetCountTake,
  GetFirst,
  GetFirstTake,
  GetLargest,
  GetLargestTake,
  GetLast,
  GetLastTake,
  GetLength,
  GetLengthTake,
  GetSmallest,
  GetSmallestTake,
  GetSum,
  GetSumTake,
} from './get'
import type {
  HasItem,
  HasItemTake,
  HasKey,
  HasKeyTake,
  HasKeys,
  HasKeysTake,
  HasPattern,
  HasPatternTake,
  HasPrefix,
  HasPrefixTake,
  HasSubstring,
  HasSubstringTake,
  HasSuffix,
  HasSuffixTake,
  HasValue,
  HasValueTake,
} from './has'
import type {
  IsAbove,
  IsAboveTake,
  IsAll,
  IsAllTake,
  IsAlwaysFalse,
  IsAlwaysFalseTake,
  IsAlwaysTrue,
  IsAlwaysTrueTake,
  IsAmong,
  IsAmongTake,
  IsAny,
  IsAnyTake,
  IsBelow,
  IsBelowTake,
  IsBetween,
  IsBetweenTake,
  IsBlank,
  IsBlankTake,
  IsBoolean,
  IsBooleanLiteral,
  IsBooleanLiteralTake,
  IsBooleanTake,
  IsCodeLiteral,
  IsCodeLiteralTake,
  IsDateLiteral,
  IsDateLiteralTake,
  IsDateRange,
  IsDateRangeTake,
  IsDecimal,
  IsDecimalLiteral,
  IsDecimalLiteralTake,
  IsDecimalRange,
  IsDecimalRangeTake,
  IsDecimalTake,
  IsEmail,
  IsEmailTake,
  IsEqual,
  IsEqualTake,
  IsFinite,
  IsFiniteTake,
  IsInteger,
  IsIntegerLiteral,
  IsIntegerLiteralTake,
  IsIntegerRange,
  IsIntegerRangeTake,
  IsIntegerTake,
  IsIpa,
  IsIpaBroad,
  IsIpaBroadTake,
  IsIpaNarrow,
  IsIpaNarrowTake,
  IsIpaTake,
  IsList,
  IsListTake,
  IsLiteralString,
  IsLiteralStringTake,
  IsLowercase,
  IsLowercaseTake,
  IsMap,
  IsMapTake,
  IsMax,
  IsMaxTake,
  IsMin,
  IsMinTake,
  IsNegative,
  IsNegativeTake,
  IsNot,
  IsNotTake,
  IsNull,
  IsNullTake,
  IsOne,
  IsOneTake,
  IsPositive,
  IsPositiveTake,
  IsPresent,
  IsPresentTake,
  IsSlug,
  IsSlugTake,
  IsString,
  IsStringPattern,
  IsStringPatternTake,
  IsStringTake,
  IsUppercase,
  IsUppercaseTake,
  IsUrl,
  IsUrlTake,
  IsUuid,
  IsUuidTake,
  IsWhole,
  IsWholeTake,
  IsZero,
  IsZeroTake,
} from './is'
import type {
  MakeDifference,
  MakeDifferenceTake,
  MakeLowercase,
  MakeLowercaseTake,
  MakeNow,
  MakeNowTake,
  MakeProduct,
  MakeProductTake,
  MakeQuotient,
  MakeQuotientTake,
  MakeSum,
  MakeSumTake,
  MakeTrimmed,
  MakeTrimmedTake,
  MakeUppercase,
  MakeUppercaseTake,
  MakeUuid,
  MakeUuidTake,
} from './make'
import type { Validate, ValidateTake } from './validate'
import type {
  WalkChunk,
  WalkChunkTake,
  WalkDistinct,
  WalkDistinctTake,
  WalkFilter,
  WalkFilterTake,
  WalkMap,
  WalkMapTake,
  WalkReduce,
  WalkReduceTake,
} from './walk'

export type Code = {
  'flow:is:always_false': {
    take: IsAlwaysFalseTake
    make: IsAlwaysFalse
  }
  'flow:is:always_true': { take: IsAlwaysTrueTake; make: IsAlwaysTrue }
  'flow:is:above': { take: IsAboveTake; make: IsAbove }
  'flow:is:all': { take: IsAllTake; make: IsAll }
  'flow:is:among': { take: IsAmongTake; make: IsAmong }
  'flow:is:any': { take: IsAnyTake; make: IsAny }
  'flow:is:below': { take: IsBelowTake; make: IsBelow }
  'flow:is:between': { take: IsBetweenTake; make: IsBetween }
  'flow:is:blank': { take: IsBlankTake; make: IsBlank }
  'flow:is:boolean': { take: IsBooleanTake; make: IsBoolean }
  'flow:is:boolean-literal': {
    take: IsBooleanLiteralTake
    make: IsBooleanLiteral
  }
  'flow:is:code-literal': {
    take: IsCodeLiteralTake
    make: IsCodeLiteral
  }
  'flow:is:date-literal': {
    take: IsDateLiteralTake
    make: IsDateLiteral
  }
  'flow:is:date-range': { take: IsDateRangeTake; make: IsDateRange }
  'flow:is:decimal': { take: IsDecimalTake; make: IsDecimal }
  'flow:is:decimal-literal': {
    take: IsDecimalLiteralTake
    make: IsDecimalLiteral
  }
  'flow:is:decimal-range': {
    take: IsDecimalRangeTake
    make: IsDecimalRange
  }
  'flow:is:email': { take: IsEmailTake; make: IsEmail }
  'flow:is:equal': { take: IsEqualTake; make: IsEqual }
  'flow:is:finite': { take: IsFiniteTake; make: IsFinite }
  'flow:is:integer': { take: IsIntegerTake; make: IsInteger }
  'flow:is:integer-literal': {
    take: IsIntegerLiteralTake
    make: IsIntegerLiteral
  }
  'flow:is:integer-range': {
    take: IsIntegerRangeTake
    make: IsIntegerRange
  }
  'flow:is:ipa': { take: IsIpaTake; make: IsIpa }
  'flow:is:ipa:broad': { take: IsIpaBroadTake; make: IsIpaBroad }
  'flow:is:ipa:narrow': { take: IsIpaNarrowTake; make: IsIpaNarrow }
  'flow:is:list': { take: IsListTake; make: IsList }
  'flow:is:literal-string': {
    take: IsLiteralStringTake
    make: IsLiteralString
  }
  'flow:is:lowercase': { take: IsLowercaseTake; make: IsLowercase }
  'flow:is:map': { take: IsMapTake; make: IsMap }
  'flow:is:max': { take: IsMaxTake; make: IsMax }
  'flow:is:min': { take: IsMinTake; make: IsMin }
  'flow:is:negative': { take: IsNegativeTake; make: IsNegative }
  'flow:is:not': { take: IsNotTake; make: IsNot }
  'flow:is:null': { take: IsNullTake; make: IsNull }
  'flow:is:one': { take: IsOneTake; make: IsOne }
  'flow:is:positive': { take: IsPositiveTake; make: IsPositive }
  'flow:is:present': { take: IsPresentTake; make: IsPresent }
  'flow:is:slug': { take: IsSlugTake; make: IsSlug }
  'flow:is:string': { take: IsStringTake; make: IsString }
  'flow:is:string-pattern': {
    take: IsStringPatternTake
    make: IsStringPattern
  }
  'flow:is:uppercase': { take: IsUppercaseTake; make: IsUppercase }
  'flow:is:url': { take: IsUrlTake; make: IsUrl }
  'flow:is:uuid': { take: IsUuidTake; make: IsUuid }
  'flow:is:whole': { take: IsWholeTake; make: IsWhole }
  'flow:is:zero': { take: IsZeroTake; make: IsZero }
  'flow:make:difference': {
    take: MakeDifferenceTake
    make: MakeDifference
  }
  'flow:make:lowercase': {
    take: MakeLowercaseTake
    make: MakeLowercase
  }
  'flow:make:now': { take: MakeNowTake; make: MakeNow }
  'flow:make:product': { take: MakeProductTake; make: MakeProduct }
  'flow:make:quotient': { take: MakeQuotientTake; make: MakeQuotient }
  'flow:make:sum': { take: MakeSumTake; make: MakeSum }
  'flow:make:trimmed': { take: MakeTrimmedTake; make: MakeTrimmed }
  'flow:make:uppercase': {
    take: MakeUppercaseTake
    make: MakeUppercase
  }
  'flow:make:uuid': { take: MakeUuidTake; make: MakeUuid }
  'flow:get:average': { take: GetAverageTake; make: GetAverage }
  'flow:get:count': { take: GetCountTake; make: GetCount }
  'flow:get:first': { take: GetFirstTake; make: GetFirst }
  'flow:get:largest': { take: GetLargestTake; make: GetLargest }
  'flow:get:last': { take: GetLastTake; make: GetLast }
  'flow:get:length': { take: GetLengthTake; make: GetLength }
  'flow:get:smallest': { take: GetSmallestTake; make: GetSmallest }
  'flow:get:sum': { take: GetSumTake; make: GetSum }
  'flow:has:item': { take: HasItemTake; make: HasItem }
  'flow:has:key': { take: HasKeyTake; make: HasKey }
  'flow:has:keys': { take: HasKeysTake; make: HasKeys }
  'flow:has:pattern': { take: HasPatternTake; make: HasPattern }
  'flow:has:prefix': { take: HasPrefixTake; make: HasPrefix }
  'flow:has:substring': { take: HasSubstringTake; make: HasSubstring }
  'flow:has:suffix': { take: HasSuffixTake; make: HasSuffix }
  'flow:has:value': { take: HasValueTake; make: HasValue }
  'flow:format:capitalized': {
    take: FormatCapitalizedTake
    make: FormatCapitalized
  }
  'flow:format:currency': {
    take: FormatCurrencyTake
    make: FormatCurrency
  }
  'flow:format:date': { take: FormatDateTake; make: FormatDate }
  'flow:format:joined': { take: FormatJoinedTake; make: FormatJoined }
  'flow:format:lowercase': {
    take: FormatLowercaseTake
    make: FormatLowercase
  }
  'flow:format:number': { take: FormatNumberTake; make: FormatNumber }
  'flow:format:percent': {
    take: FormatPercentTake
    make: FormatPercent
  }
  'flow:format:plural': { take: FormatPluralTake; make: FormatPlural }
  'flow:format:relative': {
    take: FormatRelativeTake
    make: FormatRelative
  }
  'flow:format:replaced': {
    take: FormatReplacedTake
    make: FormatReplaced
  }
  'flow:format:reversed': {
    take: FormatReversedTake
    make: FormatReversed
  }
  'flow:format:split': { take: FormatSplitTake; make: FormatSplit }
  'flow:format:time': { take: FormatTimeTake; make: FormatTime }
  'flow:format:truncated': {
    take: FormatTruncatedTake
    make: FormatTruncated
  }
  'flow:format:uppercase': {
    take: FormatUppercaseTake
    make: FormatUppercase
  }
  'flow:branch': { take: BranchTake; make: Branch }
  'flow:bind': { take: BindTake; make: Bind }
  'flow:validate': { take: ValidateTake; make: Validate }
  'flow:walk:chunk': { take: WalkChunkTake; make: WalkChunk }
  'flow:walk:distinct': { take: WalkDistinctTake; make: WalkDistinct }
  'flow:walk:filter': { take: WalkFilterTake; make: WalkFilter }
  'flow:walk:map': { take: WalkMapTake; make: WalkMap }
  'flow:walk:reduce': { take: WalkReduceTake; make: WalkReduce }
}

export const CodeLink = {
  'flow:bind': 1,
  'flow:branch': 2,
  'flow:format:capitalized': 3,
  'flow:format:currency': 4,
  'flow:format:date': 5,
  'flow:format:joined': 6,
  'flow:format:lowercase': 7,
  'flow:format:number': 8,
  'flow:format:percent': 9,
  'flow:format:plural': 10,
  'flow:format:relative': 11,
  'flow:format:replaced': 12,
  'flow:format:reversed': 13,
  'flow:format:split': 14,
  'flow:format:time': 15,
  'flow:format:truncated': 16,
  'flow:format:uppercase': 17,
  'flow:get:average': 18,
  'flow:get:count': 19,
  'flow:get:first': 20,
  'flow:get:largest': 21,
  'flow:get:last': 22,
  'flow:get:length': 23,
  'flow:get:smallest': 24,
  'flow:get:sum': 25,
  'flow:has:item': 26,
  'flow:has:key': 27,
  'flow:has:keys': 28,
  'flow:has:pattern': 29,
  'flow:has:prefix': 30,
  'flow:has:substring': 31,
  'flow:has:suffix': 32,
  'flow:has:value': 33,
  'flow:is:above': 34,
  'flow:is:all': 35,
  'flow:is:always_false': 36,
  'flow:is:always_true': 37,
  'flow:is:among': 38,
  'flow:is:any': 39,
  'flow:is:below': 40,
  'flow:is:between': 41,
  'flow:is:blank': 42,
  'flow:is:boolean': 43,
  'flow:is:boolean-literal': 44,
  'flow:is:code-literal': 45,
  'flow:is:date-literal': 46,
  'flow:is:date-range': 47,
  'flow:is:decimal': 48,
  'flow:is:decimal-literal': 49,
  'flow:is:decimal-range': 50,
  'flow:is:email': 51,
  'flow:is:equal': 52,
  'flow:is:finite': 53,
  'flow:is:integer': 54,
  'flow:is:integer-literal': 55,
  'flow:is:integer-range': 56,
  'flow:is:ipa': 57,
  'flow:is:ipa:broad': 58,
  'flow:is:ipa:narrow': 59,
  'flow:is:list': 60,
  'flow:is:literal-string': 61,
  'flow:is:lowercase': 62,
  'flow:is:map': 63,
  'flow:is:max': 64,
  'flow:is:min': 65,
  'flow:is:negative': 66,
  'flow:is:not': 67,
  'flow:is:null': 68,
  'flow:is:one': 69,
  'flow:is:positive': 70,
  'flow:is:present': 71,
  'flow:is:slug': 72,
  'flow:is:string': 73,
  'flow:is:string-pattern': 74,
  'flow:is:uppercase': 75,
  'flow:is:url': 76,
  'flow:is:uuid': 77,
  'flow:is:whole': 78,
  'flow:is:zero': 79,
  'flow:make:difference': 80,
  'flow:make:lowercase': 81,
  'flow:make:now': 82,
  'flow:make:product': 83,
  'flow:make:quotient': 84,
  'flow:make:sum': 85,
  'flow:make:trimmed': 86,
  'flow:make:uppercase': 87,
  'flow:make:uuid': 88,
  'flow:validate': 89,
  'flow:walk:chunk': 90,
  'flow:walk:distinct': 91,
  'flow:walk:filter': 92,
  'flow:walk:map': 93,
  'flow:walk:reduce': 94,
} as const

export type CodeLink = (typeof CodeLink)[keyof typeof CodeLink]

export default Code
