// Generated by `Make.save()`. Do not edit.

import type {
  FormatCapitalized,
  FormatCapitalizedTake,
  FormatCurrency,
  FormatCurrencyTake,
  FormatDate,
  FormatDateTake,
  FormatJoined,
  FormatJoinedTake,
  FormatNumber,
  FormatNumberTake,
  FormatPercent,
  FormatPercentTake,
  FormatPlural,
  FormatPluralTake,
  FormatRelative,
  FormatRelativeTake,
  FormatReplaced,
  FormatReplacedTake,
  FormatReversed,
  FormatReversedTake,
  FormatSplit,
  FormatSplitTake,
  FormatTime,
  FormatTimeTake,
  FormatTruncated,
  FormatTruncatedTake,
} from './format'
import type {
  GetAverage,
  GetAverageTake,
  GetCount,
  GetCountTake,
  GetFirst,
  GetFirstTake,
  GetLargest,
  GetLargestTake,
  GetLast,
  GetLastTake,
  GetLength,
  GetLengthTake,
  GetSmallest,
  GetSmallestTake,
  GetSum,
  GetSumTake,
} from './get'
import type {
  HasItem,
  HasItemTake,
  HasKey,
  HasKeyTake,
  HasKeys,
  HasKeysTake,
  HasPattern,
  HasPatternTake,
  HasPrefix,
  HasPrefixTake,
  HasSubstring,
  HasSubstringTake,
  HasSuffix,
  HasSuffixTake,
  HasValue,
  HasValueTake,
} from './has'
import type {
  IsAbove,
  IsAboveTake,
  IsAll,
  IsAllTake,
  IsAlwaysFalse,
  IsAlwaysFalseTake,
  IsAlwaysTrue,
  IsAlwaysTrueTake,
  IsAmong,
  IsAmongTake,
  IsAny,
  IsAnyTake,
  IsBelow,
  IsBelowTake,
  IsBetween,
  IsBetweenTake,
  IsBlank,
  IsBlankTake,
  IsBoolean,
  IsBooleanTake,
  IsDecimal,
  IsDecimalTake,
  IsEmail,
  IsEmailTake,
  IsEqual,
  IsEqualTake,
  IsFinite,
  IsFiniteTake,
  IsInteger,
  IsIntegerTake,
  IsIpa,
  IsIpaBroad,
  IsIpaBroadTake,
  IsIpaNarrow,
  IsIpaNarrowTake,
  IsIpaTake,
  IsList,
  IsListTake,
  IsLowercase,
  IsLowercaseTake,
  IsMap,
  IsMapTake,
  IsMax,
  IsMaxTake,
  IsMin,
  IsMinTake,
  IsNegative,
  IsNegativeTake,
  IsNot,
  IsNotTake,
  IsNull,
  IsNullTake,
  IsOne,
  IsOneTake,
  IsPositive,
  IsPositiveTake,
  IsSlug,
  IsSlugTake,
  IsString,
  IsStringTake,
  IsUppercase,
  IsUppercaseTake,
  IsUrl,
  IsUrlTake,
  IsUuid,
  IsUuidTake,
  IsWhole,
  IsWholeTake,
  IsZero,
  IsZeroTake,
} from './is'
import type {
  MakeDifference,
  MakeDifferenceTake,
  MakeLowercase,
  MakeLowercaseTake,
  MakeProduct,
  MakeProductTake,
  MakeQuotient,
  MakeQuotientTake,
  MakeSum,
  MakeSumTake,
  MakeTrimmed,
  MakeTrimmedTake,
  MakeUppercase,
  MakeUppercaseTake,
} from './make'

export type Code = {
  'flow:is:always_false': { take: IsAlwaysFalseTake; make: IsAlwaysFalse }
  'flow:is:always_true': { take: IsAlwaysTrueTake; make: IsAlwaysTrue }
  'flow:is:above': { take: IsAboveTake; make: IsAbove }
  'flow:is:all': { take: IsAllTake; make: IsAll }
  'flow:is:among': { take: IsAmongTake; make: IsAmong }
  'flow:is:any': { take: IsAnyTake; make: IsAny }
  'flow:is:below': { take: IsBelowTake; make: IsBelow }
  'flow:is:between': { take: IsBetweenTake; make: IsBetween }
  'flow:is:blank': { take: IsBlankTake; make: IsBlank }
  'flow:is:boolean': { take: IsBooleanTake; make: IsBoolean }
  'flow:is:decimal': { take: IsDecimalTake; make: IsDecimal }
  'flow:is:email': { take: IsEmailTake; make: IsEmail }
  'flow:is:equal': { take: IsEqualTake; make: IsEqual }
  'flow:is:finite': { take: IsFiniteTake; make: IsFinite }
  'flow:is:integer': { take: IsIntegerTake; make: IsInteger }
  'flow:is:ipa': { take: IsIpaTake; make: IsIpa }
  'flow:is:ipa:broad': { take: IsIpaBroadTake; make: IsIpaBroad }
  'flow:is:ipa:narrow': { take: IsIpaNarrowTake; make: IsIpaNarrow }
  'flow:is:list': { take: IsListTake; make: IsList }
  'flow:is:lowercase': { take: IsLowercaseTake; make: IsLowercase }
  'flow:is:map': { take: IsMapTake; make: IsMap }
  'flow:is:max': { take: IsMaxTake; make: IsMax }
  'flow:is:min': { take: IsMinTake; make: IsMin }
  'flow:is:negative': { take: IsNegativeTake; make: IsNegative }
  'flow:is:not': { take: IsNotTake; make: IsNot }
  'flow:is:null': { take: IsNullTake; make: IsNull }
  'flow:is:one': { take: IsOneTake; make: IsOne }
  'flow:is:positive': { take: IsPositiveTake; make: IsPositive }
  'flow:is:slug': { take: IsSlugTake; make: IsSlug }
  'flow:is:string': { take: IsStringTake; make: IsString }
  'flow:is:uppercase': { take: IsUppercaseTake; make: IsUppercase }
  'flow:is:url': { take: IsUrlTake; make: IsUrl }
  'flow:is:uuid': { take: IsUuidTake; make: IsUuid }
  'flow:is:whole': { take: IsWholeTake; make: IsWhole }
  'flow:is:zero': { take: IsZeroTake; make: IsZero }
  'flow:make:difference': { take: MakeDifferenceTake; make: MakeDifference }
  'flow:make:lowercase': { take: MakeLowercaseTake; make: MakeLowercase }
  'flow:make:product': { take: MakeProductTake; make: MakeProduct }
  'flow:make:quotient': { take: MakeQuotientTake; make: MakeQuotient }
  'flow:make:sum': { take: MakeSumTake; make: MakeSum }
  'flow:make:trimmed': { take: MakeTrimmedTake; make: MakeTrimmed }
  'flow:make:uppercase': { take: MakeUppercaseTake; make: MakeUppercase }
  'flow:get:average': { take: GetAverageTake; make: GetAverage }
  'flow:get:count': { take: GetCountTake; make: GetCount }
  'flow:get:first': { take: GetFirstTake; make: GetFirst }
  'flow:get:largest': { take: GetLargestTake; make: GetLargest }
  'flow:get:last': { take: GetLastTake; make: GetLast }
  'flow:get:length': { take: GetLengthTake; make: GetLength }
  'flow:get:smallest': { take: GetSmallestTake; make: GetSmallest }
  'flow:get:sum': { take: GetSumTake; make: GetSum }
  'flow:has:item': { take: HasItemTake; make: HasItem }
  'flow:has:key': { take: HasKeyTake; make: HasKey }
  'flow:has:keys': { take: HasKeysTake; make: HasKeys }
  'flow:has:pattern': { take: HasPatternTake; make: HasPattern }
  'flow:has:prefix': { take: HasPrefixTake; make: HasPrefix }
  'flow:has:substring': { take: HasSubstringTake; make: HasSubstring }
  'flow:has:suffix': { take: HasSuffixTake; make: HasSuffix }
  'flow:has:value': { take: HasValueTake; make: HasValue }
  'flow:format:capitalized': { take: FormatCapitalizedTake; make: FormatCapitalized }
  'flow:format:currency': { take: FormatCurrencyTake; make: FormatCurrency }
  'flow:format:date': { take: FormatDateTake; make: FormatDate }
  'flow:format:joined': { take: FormatJoinedTake; make: FormatJoined }
  'flow:format:number': { take: FormatNumberTake; make: FormatNumber }
  'flow:format:percent': { take: FormatPercentTake; make: FormatPercent }
  'flow:format:plural': { take: FormatPluralTake; make: FormatPlural }
  'flow:format:relative': { take: FormatRelativeTake; make: FormatRelative }
  'flow:format:replaced': { take: FormatReplacedTake; make: FormatReplaced }
  'flow:format:reversed': { take: FormatReversedTake; make: FormatReversed }
  'flow:format:split': { take: FormatSplitTake; make: FormatSplit }
  'flow:format:time': { take: FormatTimeTake; make: FormatTime }
  'flow:format:truncated': { take: FormatTruncatedTake; make: FormatTruncated }
}

export const CodeLink = {
  'flow:format:capitalized': 1,
  'flow:format:currency': 2,
  'flow:format:date': 3,
  'flow:format:joined': 4,
  'flow:format:number': 5,
  'flow:format:percent': 6,
  'flow:format:plural': 7,
  'flow:format:relative': 8,
  'flow:format:replaced': 9,
  'flow:format:reversed': 10,
  'flow:format:split': 11,
  'flow:format:time': 12,
  'flow:format:truncated': 13,
  'flow:get:average': 14,
  'flow:get:count': 15,
  'flow:get:first': 16,
  'flow:get:largest': 17,
  'flow:get:last': 18,
  'flow:get:length': 19,
  'flow:get:smallest': 20,
  'flow:get:sum': 21,
  'flow:has:item': 22,
  'flow:has:key': 23,
  'flow:has:keys': 24,
  'flow:has:pattern': 25,
  'flow:has:prefix': 26,
  'flow:has:substring': 27,
  'flow:has:suffix': 28,
  'flow:has:value': 29,
  'flow:is:above': 30,
  'flow:is:all': 31,
  'flow:is:always_false': 32,
  'flow:is:always_true': 33,
  'flow:is:among': 34,
  'flow:is:any': 35,
  'flow:is:below': 36,
  'flow:is:between': 37,
  'flow:is:blank': 38,
  'flow:is:boolean': 39,
  'flow:is:decimal': 40,
  'flow:is:email': 41,
  'flow:is:equal': 42,
  'flow:is:finite': 43,
  'flow:is:integer': 44,
  'flow:is:ipa': 45,
  'flow:is:ipa:broad': 46,
  'flow:is:ipa:narrow': 47,
  'flow:is:list': 48,
  'flow:is:lowercase': 49,
  'flow:is:map': 50,
  'flow:is:max': 51,
  'flow:is:min': 52,
  'flow:is:negative': 53,
  'flow:is:not': 54,
  'flow:is:null': 55,
  'flow:is:one': 56,
  'flow:is:positive': 57,
  'flow:is:slug': 58,
  'flow:is:string': 59,
  'flow:is:uppercase': 60,
  'flow:is:url': 61,
  'flow:is:uuid': 62,
  'flow:is:whole': 63,
  'flow:is:zero': 64,
  'flow:make:difference': 65,
  'flow:make:lowercase': 66,
  'flow:make:product': 67,
  'flow:make:quotient': 68,
  'flow:make:sum': 69,
  'flow:make:trimmed': 70,
  'flow:make:uppercase': 71,
} as const

export type CodeLink = (typeof CodeLink)[keyof typeof CodeLink]

export default Code
