/**
 * The standard catalog Book.
 *
 * Aggregates every authored Form / Flow declaration across
 * the verb groups (`is/`, `make/`, `get/`, …) into a single
 * `Book` value. Consumers register it with `make.load(...)`
 * to pull the catalog into their bundle.
 *
 * Handlers live in each group's sibling `flow.ts` file; the
 * runtime wires them in via the `Base` class.
 *
 * The bundled `Code` type is generated by `Make.save()` into
 * `./code.ts` (re-exported below) — the kysely-DB equivalent
 * for runtime type inference.
 */

import type { Book, Cast } from '@/form'

import * as is_flows from './is/make'
import * as make_flows from './make/make'
import * as get_flows from './get/make'
import * as has_flows from './has/make'
import * as format_flows from './format/make'

import * as is_hooks from './is/flow'
import * as make_hooks from './make/flow'
import * as get_hooks from './get/flow'
import * as has_hooks from './has/flow'
import * as format_hooks from './format/flow'

import { CodeLink } from './code'

const cast: Cast[] = [
  ...Object.values(is_flows),
  ...Object.values(make_flows),
  ...Object.values(get_flows),
  ...Object.values(has_flows),
  ...Object.values(format_flows),
]

const call = {
  ...is_hooks,
  ...make_hooks,
  ...get_hooks,
  ...has_hooks,
  ...format_hooks,
} as const

const standard: Book = {
  host: 'cluesurf',
  name: 'calm',
  cast,
  call,
  code: CodeLink,
}

export default standard

/**
 * The standard catalog's hook implementations, keyed by the
 * exported-constant name. Exported separately for consumers
 * that want to compose call tables; the same map is also on
 * `standard.call` so a single `base.load(standard)` is enough
 * for typical setups.
 */
export const hooks = call

// Re-export the generated `Code` type and `CodeLink` integer-id
// table from the same folder so consumers can:
//
//   import type { Code } from '@cluesurf/calm/book'
//   import { CodeLink } from '@cluesurf/calm/book'
export type { Code } from './code'
export { CodeLink }
export type { CodeLink as CodeLinkValue } from './code'
