/**
 * The standard catalog Book.
 *
 * Aggregates every authored Form / Flow declaration across
 * the verb groups (`is/`, `make/`, `get/`, …) into a single
 * `Book` value. Consumers register it with `make.load(...)`
 * to pull the catalog into their bundle.
 *
 * Handlers live in each group's sibling `flow.ts` file; the
 * runtime wires them in via the `Base` class.
 *
 * The bundled `Code` type is generated by `Make.save()` into
 * `./code.ts` (re-exported below) — the kysely-DB equivalent
 * for runtime type inference.
 */

import type { Book, Cast } from '@/form'

import * as isFlows from './is/make'
import * as makeFlows from './make/make'
import * as getFlows from './get/make'
import * as hasFlows from './has/make'
import * as formatFlows from './format/make'
import * as forkFlows from './fork/make'
import * as bindFlows from './bind/make'
import * as validateFlows from './validate/make'
import * as walkFlows from './walk/make'
import * as findFlows from './find/make'

import * as isHooks from './is/flow'
import * as makeHooks from './make/flow'
import * as getHooks from './get/flow'
import * as hasHooks from './has/flow'
import * as formatHooks from './format/flow'
import * as forkHooks from './fork/flow'
import * as bindHooks from './bind/flow'
import * as validateHooks from './validate/flow'
import * as walkHooks from './walk/flow'
import * as findHooks from './find/flow'

import { CodeLink } from './code'

const cast: Cast[] = [
  ...Object.values(isFlows),
  ...Object.values(makeFlows),
  ...Object.values(getFlows),
  ...Object.values(hasFlows),
  ...Object.values(formatFlows),
  ...Object.values(forkFlows),
  ...Object.values(bindFlows),
  ...Object.values(validateFlows),
  ...Object.values(walkFlows),
  ...Object.values(findFlows),
]

const call = {
  ...isHooks,
  ...makeHooks,
  ...getHooks,
  ...hasHooks,
  ...formatHooks,
  ...forkHooks,
  ...bindHooks,
  ...validateHooks,
  ...walkHooks,
  ...findHooks,
} as const

const beadBook: Book = {
  host: 'cluesurf',
  name: 'bead',
  cast,
  call,
  code: CodeLink,
}

export default beadBook

// Re-export the generated `Code` type and `CodeLink` integer-id
// table from the same folder so consumers can:
//
//   import type { Code } from '@cluesurf/bead/book'
//   import { CodeLink } from '@cluesurf/bead/book'
export type { Code } from './code'
export { CodeLink }
export type { CodeLink as CodeLinkValue } from './code'
