/**
 * The standard catalog Book.
 *
 * Aggregates every authored Form / Flow declaration across the
 * verb groups (`is/`, `make/`, `get/`, …) into a single `Book`
 * value. Consumers register it with `make.load(...)` to pull
 * the catalog into their bundle.
 *
 * Handlers live in each verb's sibling `flow.ts` as a default-
 * exported map keyed by the colon-scoped Flow path.
 *
 * The bundled `Code` type is generated by `Make.save()` into
 * `./code.ts` (re-exported below).
 */

import type { Book, Make } from '@/form'

import * as isFlows from './is/make'
import * as makeFlows from './make/make'
import * as getFlows from './get/make'
import * as hasFlows from './has/make'
import * as formatFlows from './format/make'
import * as branchFlows from './branch/make'
import * as bindFlows from './bind/make'
import * as validateFlows from './validate/make'
import * as walkFlows from './walk/make'

import isFlow from './is/flow'
import makeFlow from './make/flow'
import getFlow from './get/flow'
import hasFlow from './has/flow'
import formatFlow from './format/flow'
import branchFlow from './branch/flow'
import bindFlow from './bind/flow'
import validateFlow from './validate/flow'
import walkFlow from './walk/flow'

import { CodeLink } from './code'

const make: Make[] = [
  ...Object.values(isFlows),
  ...Object.values(makeFlows),
  ...Object.values(getFlows),
  ...Object.values(hasFlows),
  ...Object.values(formatFlows),
  ...Object.values(branchFlows),
  ...Object.values(bindFlows),
  ...Object.values(validateFlows),
  ...Object.values(walkFlows),
]

const flow = {
  ...isFlow,
  ...makeFlow,
  ...getFlow,
  ...hasFlow,
  ...formatFlow,
  ...branchFlow,
  ...bindFlow,
  ...validateFlow,
  ...walkFlow,
}

const beadBook: Book = {
  host: 'cluesurf',
  name: 'leaf',
  make,
  flow,
  code: CodeLink,
}

export default beadBook

// Re-export the generated `Code` type and `CodeLink` integer-id
// table.
export type { Code } from './code'
export { CodeLink }
export type { CodeLink as CodeLinkValue } from './code'
