// Generated by `Make.save()`. Do not edit.

import { z } from 'zod'
import type {
  MakeDifference,
  MakeDifferenceTake,
  MakeLowercase,
  MakeLowercaseTake,
  MakeProduct,
  MakeProductTake,
  MakeQuotient,
  MakeQuotientTake,
  MakeSum,
  MakeSumTake,
  MakeTrimmed,
  MakeTrimmedTake,
  MakeUppercase,
  MakeUppercaseTake,
} from '.'

export const MakeDifferenceTakeForm = z.object({
  a: z.number(),
  b: z.number(),
}) satisfies z.ZodType<MakeDifferenceTake>
export const MakeDifferenceForm = z.number() satisfies z.ZodType<MakeDifference>

export const MakeLowercaseTakeForm = z.object({
  text: z.string(),
}) satisfies z.ZodType<MakeLowercaseTake>
export const MakeLowercaseForm = z.string() satisfies z.ZodType<MakeLowercase>

export const MakeProductTakeForm = z.object({
  a: z.number(),
  b: z.number(),
}) satisfies z.ZodType<MakeProductTake>
export const MakeProductForm = z.number() satisfies z.ZodType<MakeProduct>

export const MakeQuotientTakeForm = z.object({
  a: z.number(),
  b: z.number(),
}) satisfies z.ZodType<MakeQuotientTake>
export const MakeQuotientForm = z.number() satisfies z.ZodType<MakeQuotient>

export const MakeSumTakeForm = z.object({
  a: z.number(),
  b: z.number(),
}) satisfies z.ZodType<MakeSumTake>
export const MakeSumForm = z.number() satisfies z.ZodType<MakeSum>

export const MakeTrimmedTakeForm = z.object({
  text: z.string(),
}) satisfies z.ZodType<MakeTrimmedTake>
export const MakeTrimmedForm = z.string() satisfies z.ZodType<MakeTrimmed>

export const MakeUppercaseTakeForm = z.object({
  text: z.string(),
}) satisfies z.ZodType<MakeUppercaseTake>
export const MakeUppercaseForm = z.string() satisfies z.ZodType<MakeUppercase>
