// Generated by `Make.save()`. Do not edit.

export type MakeDifferenceTake = { a: number; b: number }
export type MakeDifference = number

export type MakeLowercaseTake = { text: string }
export type MakeLowercase = string

export type MakeNowTake = unknown
export type MakeNow = Date

export type MakeProductTake = { a: number; b: number }
export type MakeProduct = number

export type MakeQuotientTake = { a: number; b: number }
export type MakeQuotient = number

export type MakeSumTake = { a: number; b: number }
export type MakeSum = number

export type MakeTrimmedTake = { text: string }
export type MakeTrimmed = string

export type MakeUppercaseTake = { text: string }
export type MakeUppercase = string

export type MakeUuidTake = unknown
export type MakeUuid = string
