// Generated by `Make.save()`. Do not edit.

export type WalkChunkTake = { items: unknown[]; size: number }
export type WalkChunk = unknown

export type WalkDistinctTake = { items: unknown[] }
export type WalkDistinct = unknown

export type WalkFilterTake = { items: unknown[]; test: unknown }
export type WalkFilter = unknown

export type WalkMapTake = { items: unknown[]; yield: unknown }
export type WalkMap = unknown

export type WalkReduceTake = {
  items: unknown[]
  initial: unknown
  yield: unknown
}
export type WalkReduce = unknown
