// =============================================================================
// Book-driven Zod codegen (consumed by `Make.save()`)
// =============================================================================

import type { Book, Cast, Form, Link, LinkMesh } from '@/form'
import {
  flowTsBase,
  toPascalCase as toPascal,
  type RenderContext as RC,
} from './shared'

const PRIMITIVE_ZOD: Record<string, string> = {
  boolean: 'z.boolean()',
  number: 'z.number()',
  decimal: 'z.number()',
  integer: 'z.number().int()',
  natural_number: 'z.number().int().nonnegative()',
  string: 'z.string()',
  uuid: 'z.string().uuid()',
  date: 'z.coerce.date()',
  timestamp: 'z.coerce.date()',
  json: 'z.any()',
  unknown: 'z.unknown()',
}

/**
 * Walk every registered Book and emit per-`save`-directory Zod
 * parsers. Each TS type alias from the matching `index.ts` gets
 * a paired `<TypeName>Form` parser locked via
 * `satisfies z.ZodType<<TypeName>>`.
 *
 * Output: `Record<save, parserFileContent>`.
 */
export function makeBookForm(books: Book[]): Record<string, string> {
  const formRegistry = new Map<string, Form>()
  for (const book of books) {
    for (const cast of book.cast ?? []) {
      if (cast.form === 'form') formRegistry.set(cast.name, cast)
    }
  }
  const ctx: RC = { forms: formRegistry }

  const groups = new Map<string, (Cast & { save?: string })[]>()
  for (const book of books) {
    for (const cast of book.cast ?? []) {
      const save =
        ('save' in cast && typeof cast.save === 'string'
          ? cast.save
          : '') ?? ''
      ;(groups.get(save) ?? groups.set(save, []).get(save)!).push(
        cast as Cast & { save?: string },
      )
    }
  }

  const out: Record<string, string> = {}
  for (const [save, casts] of groups) {
    const typeImports = new Set<string>()
    const blocks: string[][] = []

    for (const cast of casts) {
      switch (cast.form) {
        case 'form': {
          const tsName = toPascal(cast.name)
          typeImports.add(tsName)
          blocks.push([
            `export const ${tsName}Form = ${zodShape(cast.like, ctx)} satisfies z.ZodType<${tsName}>`,
          ])
          break
        }
        case 'flow': {
          const tsBase = flowTsBase(cast)
          typeImports.add(`${tsBase}Take`)
          typeImports.add(tsBase)
          blocks.push([
            `export const ${tsBase}TakeForm = ${zodShape(cast.take, ctx)} satisfies z.ZodType<${tsBase}Take>`,
            `export const ${tsBase}Form = ${zodShape(cast.make, ctx)} satisfies z.ZodType<${tsBase}>`,
          ])
          break
        }
        case 'hash': {
          const tsName = toPascal(cast.name)
          typeImports.add(tsName)
          blocks.push([
            `export const ${tsName}Form = z.record(z.string(), ${zodLink(cast.like, ctx)}) satisfies z.ZodType<${tsName}>`,
          ])
          break
        }
        case 'list': {
          const tsName = toPascal(cast.name)
          typeImports.add(tsName)
          blocks.push([
            `export const ${tsName}Form = z.array(${zodLink(cast.like, ctx)}) satisfies z.ZodType<${tsName}>`,
          ])
          break
        }
        case 'fold':
          break
      }
    }

    if (blocks.length === 0) continue

    const header = [
      '// Generated by `Make.save()`. Do not edit.',
      '',
      "import { z } from 'zod'",
    ]
    if (typeImports.size > 0) {
      const sortedTypes = [...typeImports].sort()
      const oneLine = `import type { ${sortedTypes.join(', ')} } from '.'`
      if (oneLine.length <= 80) {
        header.push(oneLine)
      } else {
        header.push('import type {')
        for (const n of sortedTypes) header.push(`  ${n},`)
        header.push("} from '.'")
      }
    }
    header.push('')

    const body = blocks.map(b => b.join('\n')).join('\n\n')
    out[save] = [...header, body, ''].join('\n')
  }
  return out
}

function zodShape(
  shape: string | LinkMesh | (string | LinkMesh)[] | undefined,
  ctx: RC,
): string {
  if (shape == null) return 'z.unknown()'
  if (typeof shape === 'string') return zodRef(shape, ctx)
  if (Array.isArray(shape)) {
    const parts = shape.map(s => zodShape(s, ctx))
    return `z.union([${parts.join(', ')}])`
  }
  const fields: string[] = []
  for (const [name, link] of Object.entries(shape)) {
    const inner = zodLink(link, ctx)
    const wrapped = link.need === false ? `${inner}.optional()` : inner
    fields.push(`  ${name}: ${wrapped},`)
  }
  return `z.object({\n${fields.join('\n')}\n})`
}

function zodLink(link: Link, ctx: RC): string {
  let inner: string
  if (typeof link.like === 'string') {
    inner = zodRef(link.like, ctx)
  } else if (Array.isArray(link.like)) {
    const parts = link.like.map(part =>
      typeof part === 'string' ? zodRef(part, ctx) : zodShape(part, ctx),
    )
    inner = `z.union([${parts.join(', ')}])`
  } else if (link.like != null && typeof link.like === 'object') {
    inner = zodShape(link.like, ctx)
  } else {
    inner = 'z.unknown()'
  }
  return link.list ? `z.array(${inner})` : inner
}

function zodRef(name: string, ctx: RC): string {
  if (PRIMITIVE_ZOD[name] != null) return PRIMITIVE_ZOD[name]!
  if (ctx.forms.has(name)) return `${toPascal(name)}Form`
  return 'z.unknown()'
}
