// Generated by `Make.save()`. Do not edit.

import { z } from 'zod'
import type {
  FormatCapitalized,
  FormatCapitalizedTake,
  FormatCurrency,
  FormatCurrencyTake,
  FormatDate,
  FormatDateTake,
  FormatJoined,
  FormatJoinedTake,
  FormatNumber,
  FormatNumberTake,
  FormatPercent,
  FormatPercentTake,
  FormatPlural,
  FormatPluralTake,
  FormatRelative,
  FormatRelativeTake,
  FormatReplaced,
  FormatReplacedTake,
  FormatReversed,
  FormatReversedTake,
  FormatSplit,
  FormatSplitTake,
  FormatTime,
  FormatTimeTake,
  FormatTruncated,
  FormatTruncatedTake,
} from '.'

export const FormatCapitalizedTakeForm = z.object({
  text: z.string(),
}) satisfies z.ZodType<FormatCapitalizedTake>
export const FormatCapitalizedForm = z.string() satisfies z.ZodType<FormatCapitalized>

export const FormatCurrencyTakeForm = z.object({
  value: z.number(),
  currency: z.string(),
  locale: z.string().optional(),
}) satisfies z.ZodType<FormatCurrencyTake>
export const FormatCurrencyForm = z.string() satisfies z.ZodType<FormatCurrency>

export const FormatDateTakeForm = z.object({
  value: z.coerce.date(),
  locale: z.string().optional(),
  style: z.string().optional(),
}) satisfies z.ZodType<FormatDateTake>
export const FormatDateForm = z.string() satisfies z.ZodType<FormatDate>

export const FormatJoinedTakeForm = z.object({
  parts: z.array(z.string()),
  separator: z.string().optional(),
}) satisfies z.ZodType<FormatJoinedTake>
export const FormatJoinedForm = z.string() satisfies z.ZodType<FormatJoined>

export const FormatNumberTakeForm = z.object({
  value: z.number(),
  locale: z.string().optional(),
  minimum: z.number().int().optional(),
  maximum: z.number().int().optional(),
}) satisfies z.ZodType<FormatNumberTake>
export const FormatNumberForm = z.string() satisfies z.ZodType<FormatNumber>

export const FormatPercentTakeForm = z.object({
  value: z.number(),
  locale: z.string().optional(),
  minimum: z.number().int().optional(),
  maximum: z.number().int().optional(),
}) satisfies z.ZodType<FormatPercentTake>
export const FormatPercentForm = z.string() satisfies z.ZodType<FormatPercent>

export const FormatPluralTakeForm = z.object({
  count: z.number().int(),
  singular: z.string(),
  plural: z.string(),
  locale: z.string().optional(),
}) satisfies z.ZodType<FormatPluralTake>
export const FormatPluralForm = z.string() satisfies z.ZodType<FormatPlural>

export const FormatRelativeTakeForm = z.object({
  value: z.coerce.date(),
  locale: z.string().optional(),
  now: z.coerce.date().optional(),
}) satisfies z.ZodType<FormatRelativeTake>
export const FormatRelativeForm = z.string() satisfies z.ZodType<FormatRelative>

export const FormatReplacedTakeForm = z.object({
  text: z.string(),
  pattern: z.string(),
  replacement: z.string(),
}) satisfies z.ZodType<FormatReplacedTake>
export const FormatReplacedForm = z.string() satisfies z.ZodType<FormatReplaced>

export const FormatReversedTakeForm = z.object({
  text: z.string(),
}) satisfies z.ZodType<FormatReversedTake>
export const FormatReversedForm = z.string() satisfies z.ZodType<FormatReversed>

export const FormatSplitTakeForm = z.object({
  text: z.string(),
  separator: z.string(),
}) satisfies z.ZodType<FormatSplitTake>
export const FormatSplitForm = z.object({
  value: z.array(z.string()),
}) satisfies z.ZodType<FormatSplit>

export const FormatTimeTakeForm = z.object({
  value: z.coerce.date(),
  locale: z.string().optional(),
  style: z.string().optional(),
}) satisfies z.ZodType<FormatTimeTake>
export const FormatTimeForm = z.string() satisfies z.ZodType<FormatTime>

export const FormatTruncatedTakeForm = z.object({
  text: z.string(),
  length: z.number().int(),
  suffix: z.string().optional(),
}) satisfies z.ZodType<FormatTruncatedTake>
export const FormatTruncatedForm = z.string() satisfies z.ZodType<FormatTruncated>
