// Generated by `Make.save()`. Do not edit.

export type ValidateTake = {
  test: boolean
  message?: string
  slug?: string
  kind?: string
}
export type Validate = {
  ok: boolean
  message?: string
  slug?: string
  kind?: string
}
