// Generated by `Make.save()`. Do not edit.

import { z } from 'zod'
import type {
  IsAbove,
  IsAboveTake,
  IsAll,
  IsAllTake,
  IsAlwaysFalse,
  IsAlwaysFalseTake,
  IsAlwaysTrue,
  IsAlwaysTrueTake,
  IsAmong,
  IsAmongTake,
  IsAny,
  IsAnyTake,
  IsBelow,
  IsBelowTake,
  IsBetween,
  IsBetweenTake,
  IsBlank,
  IsBlankTake,
  IsBoolean,
  IsBooleanTake,
  IsDecimal,
  IsDecimalTake,
  IsEmail,
  IsEmailTake,
  IsEqual,
  IsEqualTake,
  IsFinite,
  IsFiniteTake,
  IsInteger,
  IsIntegerTake,
  IsIpa,
  IsIpaBroad,
  IsIpaBroadTake,
  IsIpaNarrow,
  IsIpaNarrowTake,
  IsIpaTake,
  IsList,
  IsListTake,
  IsLowercase,
  IsLowercaseTake,
  IsMap,
  IsMapTake,
  IsMax,
  IsMaxTake,
  IsMin,
  IsMinTake,
  IsNegative,
  IsNegativeTake,
  IsNot,
  IsNotTake,
  IsNull,
  IsNullTake,
  IsOne,
  IsOneTake,
  IsPositive,
  IsPositiveTake,
  IsSlug,
  IsSlugTake,
  IsString,
  IsStringTake,
  IsUppercase,
  IsUppercaseTake,
  IsUrl,
  IsUrlTake,
  IsUuid,
  IsUuidTake,
  IsWhole,
  IsWholeTake,
  IsZero,
  IsZeroTake,
} from '.'

export const IsAlwaysFalseTakeForm = z.unknown() satisfies z.ZodType<IsAlwaysFalseTake>
export const IsAlwaysFalseForm = z.boolean() satisfies z.ZodType<IsAlwaysFalse>

export const IsAlwaysTrueTakeForm = z.unknown() satisfies z.ZodType<IsAlwaysTrueTake>
export const IsAlwaysTrueForm = z.boolean() satisfies z.ZodType<IsAlwaysTrue>

export const IsAboveTakeForm = z.object({
  this: z.unknown(),
  that: z.unknown(),
}) satisfies z.ZodType<IsAboveTake>
export const IsAboveForm = z.boolean() satisfies z.ZodType<IsAbove>

export const IsAllTakeForm = z.object({
  things: z.array(z.boolean()),
}) satisfies z.ZodType<IsAllTake>
export const IsAllForm = z.boolean() satisfies z.ZodType<IsAll>

export const IsAmongTakeForm = z.object({
  thing: z.unknown(),
  choices: z.array(z.unknown()),
}) satisfies z.ZodType<IsAmongTake>
export const IsAmongForm = z.boolean() satisfies z.ZodType<IsAmong>

export const IsAnyTakeForm = z.object({
  things: z.array(z.boolean()),
}) satisfies z.ZodType<IsAnyTake>
export const IsAnyForm = z.boolean() satisfies z.ZodType<IsAny>

export const IsBelowTakeForm = z.object({
  this: z.unknown(),
  that: z.unknown(),
}) satisfies z.ZodType<IsBelowTake>
export const IsBelowForm = z.boolean() satisfies z.ZodType<IsBelow>

export const IsBetweenTakeForm = z.object({
  thing: z.unknown(),
  min: z.unknown(),
  max: z.unknown(),
}) satisfies z.ZodType<IsBetweenTake>
export const IsBetweenForm = z.boolean() satisfies z.ZodType<IsBetween>

export const IsBlankTakeForm = z.object({
  thing: z.unknown(),
}) satisfies z.ZodType<IsBlankTake>
export const IsBlankForm = z.boolean() satisfies z.ZodType<IsBlank>

export const IsBooleanTakeForm = z.object({
  thing: z.unknown(),
}) satisfies z.ZodType<IsBooleanTake>
export const IsBooleanForm = z.boolean() satisfies z.ZodType<IsBoolean>

export const IsDecimalTakeForm = z.object({
  thing: z.unknown(),
}) satisfies z.ZodType<IsDecimalTake>
export const IsDecimalForm = z.boolean() satisfies z.ZodType<IsDecimal>

export const IsEmailTakeForm = z.object({
  text: z.string(),
}) satisfies z.ZodType<IsEmailTake>
export const IsEmailForm = z.boolean() satisfies z.ZodType<IsEmail>

export const IsEqualTakeForm = z.object({
  this: z.unknown(),
  that: z.unknown(),
}) satisfies z.ZodType<IsEqualTake>
export const IsEqualForm = z.boolean() satisfies z.ZodType<IsEqual>

export const IsFiniteTakeForm = z.object({
  number: z.number(),
}) satisfies z.ZodType<IsFiniteTake>
export const IsFiniteForm = z.boolean() satisfies z.ZodType<IsFinite>

export const IsIntegerTakeForm = z.object({
  thing: z.unknown(),
}) satisfies z.ZodType<IsIntegerTake>
export const IsIntegerForm = z.boolean() satisfies z.ZodType<IsInteger>

export const IsIpaTakeForm = z.object({
  text: z.string(),
}) satisfies z.ZodType<IsIpaTake>
export const IsIpaForm = z.boolean() satisfies z.ZodType<IsIpa>

export const IsIpaBroadTakeForm = z.object({
  text: z.string(),
}) satisfies z.ZodType<IsIpaBroadTake>
export const IsIpaBroadForm = z.boolean() satisfies z.ZodType<IsIpaBroad>

export const IsIpaNarrowTakeForm = z.object({
  text: z.string(),
}) satisfies z.ZodType<IsIpaNarrowTake>
export const IsIpaNarrowForm = z.boolean() satisfies z.ZodType<IsIpaNarrow>

export const IsListTakeForm = z.object({
  thing: z.unknown(),
}) satisfies z.ZodType<IsListTake>
export const IsListForm = z.boolean() satisfies z.ZodType<IsList>

export const IsLowercaseTakeForm = z.object({
  text: z.string(),
}) satisfies z.ZodType<IsLowercaseTake>
export const IsLowercaseForm = z.boolean() satisfies z.ZodType<IsLowercase>

export const IsMapTakeForm = z.object({
  thing: z.unknown(),
}) satisfies z.ZodType<IsMapTake>
export const IsMapForm = z.boolean() satisfies z.ZodType<IsMap>

export const IsMaxTakeForm = z.object({
  this: z.unknown(),
  that: z.unknown(),
}) satisfies z.ZodType<IsMaxTake>
export const IsMaxForm = z.boolean() satisfies z.ZodType<IsMax>

export const IsMinTakeForm = z.object({
  this: z.unknown(),
  that: z.unknown(),
}) satisfies z.ZodType<IsMinTake>
export const IsMinForm = z.boolean() satisfies z.ZodType<IsMin>

export const IsNegativeTakeForm = z.object({
  number: z.number(),
}) satisfies z.ZodType<IsNegativeTake>
export const IsNegativeForm = z.boolean() satisfies z.ZodType<IsNegative>

export const IsNotTakeForm = z.object({
  thing: z.boolean(),
}) satisfies z.ZodType<IsNotTake>
export const IsNotForm = z.boolean() satisfies z.ZodType<IsNot>

export const IsNullTakeForm = z.object({
  thing: z.unknown(),
}) satisfies z.ZodType<IsNullTake>
export const IsNullForm = z.boolean() satisfies z.ZodType<IsNull>

export const IsOneTakeForm = z.object({
  things: z.array(z.boolean()),
}) satisfies z.ZodType<IsOneTake>
export const IsOneForm = z.boolean() satisfies z.ZodType<IsOne>

export const IsPositiveTakeForm = z.object({
  number: z.number(),
}) satisfies z.ZodType<IsPositiveTake>
export const IsPositiveForm = z.boolean() satisfies z.ZodType<IsPositive>

export const IsSlugTakeForm = z.object({
  text: z.string(),
}) satisfies z.ZodType<IsSlugTake>
export const IsSlugForm = z.boolean() satisfies z.ZodType<IsSlug>

export const IsStringTakeForm = z.object({
  thing: z.unknown(),
}) satisfies z.ZodType<IsStringTake>
export const IsStringForm = z.boolean() satisfies z.ZodType<IsString>

export const IsUppercaseTakeForm = z.object({
  text: z.string(),
}) satisfies z.ZodType<IsUppercaseTake>
export const IsUppercaseForm = z.boolean() satisfies z.ZodType<IsUppercase>

export const IsUrlTakeForm = z.object({
  text: z.string(),
}) satisfies z.ZodType<IsUrlTake>
export const IsUrlForm = z.boolean() satisfies z.ZodType<IsUrl>

export const IsUuidTakeForm = z.object({
  text: z.string(),
}) satisfies z.ZodType<IsUuidTake>
export const IsUuidForm = z.boolean() satisfies z.ZodType<IsUuid>

export const IsWholeTakeForm = z.object({
  number: z.number(),
}) satisfies z.ZodType<IsWholeTake>
export const IsWholeForm = z.boolean() satisfies z.ZodType<IsWhole>

export const IsZeroTakeForm = z.object({
  number: z.number(),
}) satisfies z.ZodType<IsZeroTake>
export const IsZeroForm = z.boolean() satisfies z.ZodType<IsZero>
