// Generated by `Make.save()`. Do not edit.

export type IsAlwaysFalseTake = unknown
export type IsAlwaysFalse = boolean

export type IsAlwaysTrueTake = unknown
export type IsAlwaysTrue = boolean

export type IsAboveTake = { this: unknown; that: unknown }
export type IsAbove = boolean

export type IsAllTake = { things: boolean[] }
export type IsAll = boolean

export type IsAmongTake = { thing: unknown; choices: unknown[] }
export type IsAmong = boolean

export type IsAnyTake = { things: boolean[] }
export type IsAny = boolean

export type IsBelowTake = { this: unknown; that: unknown }
export type IsBelow = boolean

export type IsBetweenTake = { thing: unknown; min: unknown; max: unknown }
export type IsBetween = boolean

export type IsBlankTake = { thing: unknown }
export type IsBlank = boolean

export type IsBooleanTake = { thing: unknown }
export type IsBoolean = boolean

export type IsDecimalTake = { thing: unknown }
export type IsDecimal = boolean

export type IsEmailTake = { text: string }
export type IsEmail = boolean

export type IsEqualTake = { this: unknown; that: unknown }
export type IsEqual = boolean

export type IsFiniteTake = { number: number }
export type IsFinite = boolean

export type IsIntegerTake = { thing: unknown }
export type IsInteger = boolean

export type IsIpaTake = { text: string }
export type IsIpa = boolean

export type IsIpaBroadTake = { text: string }
export type IsIpaBroad = boolean

export type IsIpaNarrowTake = { text: string }
export type IsIpaNarrow = boolean

export type IsListTake = { thing: unknown }
export type IsList = boolean

export type IsLowercaseTake = { text: string }
export type IsLowercase = boolean

export type IsMapTake = { thing: unknown }
export type IsMap = boolean

export type IsMaxTake = { this: unknown; that: unknown }
export type IsMax = boolean

export type IsMinTake = { this: unknown; that: unknown }
export type IsMin = boolean

export type IsNegativeTake = { number: number }
export type IsNegative = boolean

export type IsNotTake = { thing: boolean }
export type IsNot = boolean

export type IsNullTake = { thing: unknown }
export type IsNull = boolean

export type IsOneTake = { things: boolean[] }
export type IsOne = boolean

export type IsPositiveTake = { number: number }
export type IsPositive = boolean

export type IsSlugTake = { text: string }
export type IsSlug = boolean

export type IsStringTake = { thing: unknown }
export type IsString = boolean

export type IsUppercaseTake = { text: string }
export type IsUppercase = boolean

export type IsUrlTake = { text: string }
export type IsUrl = boolean

export type IsUuidTake = { text: string }
export type IsUuid = boolean

export type IsWholeTake = { number: number }
export type IsWhole = boolean

export type IsZeroTake = { number: number }
export type IsZero = boolean
