// Generated by `Make.save()`. Do not edit.

import { z } from 'zod'
import type {
  HasItem,
  HasItemTake,
  HasKey,
  HasKeyTake,
  HasKeys,
  HasKeysTake,
  HasPattern,
  HasPatternTake,
  HasPrefix,
  HasPrefixTake,
  HasSubstring,
  HasSubstringTake,
  HasSuffix,
  HasSuffixTake,
  HasValue,
  HasValueTake,
} from '.'

export const HasItemTakeForm = z.object({
  items: z.array(z.unknown()),
  item: z.unknown(),
}) satisfies z.ZodType<HasItemTake>
export const HasItemForm = z.boolean() satisfies z.ZodType<HasItem>

export const HasKeyTakeForm = z.object({
  thing: z.unknown(),
  key: z.string(),
}) satisfies z.ZodType<HasKeyTake>
export const HasKeyForm = z.boolean() satisfies z.ZodType<HasKey>

export const HasKeysTakeForm = z.object({
  thing: z.unknown(),
  keys: z.array(z.string()),
}) satisfies z.ZodType<HasKeysTake>
export const HasKeysForm = z.boolean() satisfies z.ZodType<HasKeys>

export const HasPatternTakeForm = z.object({
  text: z.string(),
  pattern: z.string(),
}) satisfies z.ZodType<HasPatternTake>
export const HasPatternForm = z.boolean() satisfies z.ZodType<HasPattern>

export const HasPrefixTakeForm = z.object({
  text: z.string(),
  prefix: z.string(),
}) satisfies z.ZodType<HasPrefixTake>
export const HasPrefixForm = z.boolean() satisfies z.ZodType<HasPrefix>

export const HasSubstringTakeForm = z.object({
  text: z.string(),
  substring: z.string(),
}) satisfies z.ZodType<HasSubstringTake>
export const HasSubstringForm = z.boolean() satisfies z.ZodType<HasSubstring>

export const HasSuffixTakeForm = z.object({
  text: z.string(),
  suffix: z.string(),
}) satisfies z.ZodType<HasSuffixTake>
export const HasSuffixForm = z.boolean() satisfies z.ZodType<HasSuffix>

export const HasValueTakeForm = z.object({
  thing: z.unknown(),
  value: z.unknown(),
}) satisfies z.ZodType<HasValueTake>
export const HasValueForm = z.boolean() satisfies z.ZodType<HasValue>
