// Generated by `Make.save()`. Do not edit.

export type HasItemTake = { items: unknown[]; item: unknown }
export type HasItem = boolean

export type HasKeyTake = { thing: unknown; key: string }
export type HasKey = boolean

export type HasKeysTake = { thing: unknown; keys: string[] }
export type HasKeys = boolean

export type HasPatternTake = { text: string; pattern: string }
export type HasPattern = boolean

export type HasPrefixTake = { text: string; prefix: string }
export type HasPrefix = boolean

export type HasSubstringTake = { text: string; substring: string }
export type HasSubstring = boolean

export type HasSuffixTake = { text: string; suffix: string }
export type HasSuffix = boolean

export type HasValueTake = { thing: unknown; value: unknown }
export type HasValue = boolean
