// =============================================================================
// Book-driven base codegen (consumed by `Make.save()`)
// =============================================================================

import type { Book, Make } from '@/form'
import { toPascalCase as toPascal } from './shared'

/**
 * Walk every registered Book and emit per-`save`-directory
 * runtime data files (`base.ts`). Each Hash/List with a
 * `load:` literal becomes `export const <TypeName>Base = …`.
 */
export function makeBookData(books: Book[]): Record<string, string> {
  const groups = new Map<string, (Make & { save?: string })[]>()
  for (const book of books) {
    for (const cast of book.make ?? []) {
      const save =
        ('save' in cast && typeof cast.save === 'string'
          ? cast.save
          : '') ?? ''
      ;(groups.get(save) ?? groups.set(save, []).get(save)!).push(
        cast as Make & { save?: string },
      )
    }
  }

  const out: Record<string, string> = {}
  for (const [save, casts] of groups) {
    const blocks: string[] = []
    for (const cast of casts) {
      if (
        (cast.form === 'list' || cast.form === 'hash') &&
        cast.load != null
      ) {
        const tsName = toPascal(cast.name)
        blocks.push(
          `export const ${tsName} = ${JSON.stringify(cast.load, null, 2)} as const`,
        )
      }
    }

    if (blocks.length === 0) continue

    out[save] = [
      '// Generated by `Make.save()`. Do not edit.',
      '',
      blocks.join('\n\n'),
      '',
    ].join('\n')
  }
  return out
}
