// =============================================================================
// Book-driven TS codegen (consumed by `Make.save()`)
// =============================================================================

import type { Book, Make, Form, Link, LinkMesh } from '@/form'
import { flowTsBase, toPascalCase, type RenderContext } from './shared'

const PRIMITIVE_TS: Record<string, string> = {
  boolean: 'boolean',
  number: 'number',
  decimal: 'number',
  integer: 'number',
  'number:natural': 'number',
  string: 'string',
  uuid: 'string',
  date: 'Date',
  timestamp: 'Date',
  json: 'object',
  unknown: 'unknown',
}

/**
 * Walk every registered Book and build the colon-keyed `Code`
 * aggregate type — the kysely-DB equivalent.
 *
 * Entry shapes by `form:` discriminant:
 *
 *   Flow  → `'flow:<call>:<case?>': { take, make }`
 *   Form  → `'form:<name>:<flow?>:<case?>': { cast: <ShapeType> }`
 *   Fold  → `'fold:<case>': { cast: unknown }`
 *   Hash  → `'hash:<name>': { cast: Record<string, <ItemType>> }`
 *   List  → `'list:<name>': { cast: <ItemType>[] }`
 */
export function makeBookCode(books: Book[]): {
  /** Bundled `code.ts` content — Code aggregate + CodeLink table. */
  code: string
  /**
   * Per-`save`-directory TS index files. Keyed by the cast's
   * `save` value (or `''` for casts without `save`).
   */
  link: Record<string, string>
} {
  const formRegistry = new Map<string, Form>()
  for (const book of books) {
    for (const cast of book.make ?? []) {
      if (cast.form === 'form') formRegistry.set(cast.name, cast)
    }
  }

  const ctx: RenderContext = { forms: formRegistry }

  const groups = new Map<string, (Make & { save?: string })[]>()
  for (const book of books) {
    for (const cast of book.make ?? []) {
      const save =
        ('save' in cast && typeof cast.save === 'string'
          ? cast.save
          : '') ?? ''
      ;(groups.get(save) ?? groups.set(save, []).get(save)!).push(
        cast as Make & { save?: string },
      )
    }
  }

  const link: Record<string, string> = {}
  for (const [save, casts] of groups) {
    const blocks: string[][] = []
    for (const cast of casts) {
      switch (cast.form) {
        case 'form': {
          const tsName = toPascalCase(cast.name)
          blocks.push([
            `export type ${tsName} = ${renderShape(cast.like, ctx)}`,
          ])
          break
        }
        case 'flow': {
          const tsBase = flowTsBase(cast)
          blocks.push([
            `export type ${tsBase}Take = ${renderShape(cast.take, ctx)}`,
            `export type ${tsBase} = ${renderShape(cast.make, ctx)}`,
          ])
          break
        }
        case 'hash': {
          const tsName = toPascalCase(cast.name)
          const itemType = renderLink(cast.like, ctx)
          blocks.push([
            `export type ${tsName} = Record<string, ${itemType}>`,
          ])
          break
        }
        case 'list': {
          const tsName = toPascalCase(cast.name)
          const itemType = renderLink(cast.like, ctx)
          blocks.push([`export type ${tsName} = ${itemType}[]`])
          break
        }
        case 'fold': {
          const tsName = toPascalCase(cast.case)
          blocks.push([`export type ${tsName} = unknown`])
          break
        }
      }
    }

    const body = blocks.map(b => b.join('\n')).join('\n\n')
    link[save] = [
      '// Generated by `Make.save()`. Do not edit.',
      '',
      body,
      '',
    ].join('\n')
  }

  const colonKeys: string[] = []
  const importsBySave = new Map<string, Set<string>>()
  const ensureImport = (save: string, name: string) => {
    if (save === '') return
    const set = importsBySave.get(save) ?? new Set()
    set.add(name)
    importsBySave.set(save, set)
  }

  const codeBodyLines: string[] = ['export type Code = {']
  for (const book of books) {
    for (const cast of book.make ?? []) {
      const save =
        ('save' in cast && typeof cast.save === 'string'
          ? cast.save
          : '') ?? ''
      switch (cast.form) {
        case 'flow': {
          const segments = ['flow', cast.call]
          if (cast.case) segments.push(cast.case)
          const key = segments.join(':')
          colonKeys.push(key)
          const tsBase = flowTsBase(cast)
          ensureImport(save, `${tsBase}Take`)
          ensureImport(save, tsBase)
          codeBodyLines.push(
            `  '${key}': { take: ${tsBase}Take; make: ${tsBase} }`,
          )
          break
        }
        case 'form': {
          const segments = ['form', cast.name]
          if (cast.flow) segments.push(cast.flow)
          if (cast.case) segments.push(cast.case)
          const key = segments.join(':')
          colonKeys.push(key)
          const tsName = toPascalCase(cast.name)
          ensureImport(save, tsName)
          codeBodyLines.push(`  '${key}': { cast: ${tsName} }`)
          break
        }
        case 'fold': {
          const key = `fold:${cast.case}`
          colonKeys.push(key)
          const tsName = toPascalCase(cast.case)
          ensureImport(save, tsName)
          codeBodyLines.push(`  '${key}': { cast: ${tsName} }`)
          break
        }
        case 'hash': {
          const key = `hash:${cast.name}`
          colonKeys.push(key)
          const tsName = toPascalCase(cast.name)
          ensureImport(save, tsName)
          codeBodyLines.push(`  '${key}': { cast: ${tsName} }`)
          break
        }
        case 'list': {
          const key = `list:${cast.name}`
          colonKeys.push(key)
          const tsName = toPascalCase(cast.name)
          ensureImport(save, tsName)
          codeBodyLines.push(`  '${key}': { cast: ${tsName} }`)
          break
        }
      }
    }
  }
  codeBodyLines.push('}')

  const codeLines: string[] = [
    '// Generated by `Make.save()`. Do not edit.',
    '',
  ]
  const sortedSaves = [...importsBySave.keys()].sort()
  for (const save of sortedSaves) {
    const names = [...importsBySave.get(save)!].sort()
    const oneLine = `import type { ${names.join(', ')} } from './${save}'`
    if (oneLine.length <= 80) {
      codeLines.push(oneLine)
    } else {
      codeLines.push('import type {')
      for (const n of names) codeLines.push(`  ${n},`)
      codeLines.push(`} from './${save}'`)
    }
  }
  if (sortedSaves.length > 0) codeLines.push('')

  codeLines.push(...codeBodyLines)
  codeLines.push('')

  const sortedKeys = [...new Set(colonKeys)].sort()
  codeLines.push('export const CodeLink = {')
  for (let i = 0; i < sortedKeys.length; i++) {
    codeLines.push(`  '${sortedKeys[i]}': ${i + 1},`)
  }
  codeLines.push('} as const')
  codeLines.push('')
  codeLines.push(
    'export type CodeLink = (typeof CodeLink)[keyof typeof CodeLink]',
  )
  codeLines.push('')
  codeLines.push('export default Code')
  codeLines.push('')

  return { code: codeLines.join('\n'), link }
}

function resolveRef(name: string, ctx: RenderContext): string {
  if (PRIMITIVE_TS[name] != null) return PRIMITIVE_TS[name]
  if (ctx.forms.has(name)) return toPascalCase(name)
  return name
}

/**
 * `link.take` is the enum-style allowed-values array. Each
 * element becomes a TS literal type; the union is the field's
 * type. Short-circuits the `like`-based path entirely.
 */
function takeEnumTs(values: unknown[]): string {
  return values
    .map(v => (typeof v === 'string' ? `'${v}'` : JSON.stringify(v)))
    .join(' | ')
}

function renderShape(
  shape: string | LinkMesh | (string | LinkMesh)[] | undefined,
  ctx: RenderContext,
): string {
  if (shape == null) return 'unknown'
  if (typeof shape === 'string') return resolveRef(shape, ctx)
  if (Array.isArray(shape)) {
    return shape.map(s => renderShape(s, ctx)).join(' | ')
  }
  const fields: string[] = []
  for (const [name, link] of Object.entries(shape)) {
    const optional = link.need === false ? '?' : ''
    fields.push(`${name}${optional}: ${renderLink(link, ctx)}`)
  }
  return `{ ${fields.join('; ')} }`
}

function renderLink(link: Link, ctx: RenderContext): string {
  let inner: string
  let isUnion = false
  if (Array.isArray(link.take) && link.take.length > 0) {
    inner = takeEnumTs(link.take)
    isUnion = link.take.length > 1
  } else if (typeof link.like === 'string') {
    inner = resolveRef(link.like, ctx)
  } else if (Array.isArray(link.like)) {
    inner = link.like
      .map(part =>
        typeof part === 'string'
          ? resolveRef(part, ctx)
          : renderShape(part, ctx),
      )
      .join(' | ')
    isUnion = link.like.length > 1
  } else if (link.like != null && typeof link.like === 'object') {
    inner = renderShape(link.like, ctx)
  } else {
    inner = 'unknown'
  }
  if (link.list) {
    return isUnion ? `(${inner})[]` : `${inner}[]`
  }
  return inner
}
